-- Create table for storing passwords
create table if not exists public.passwords (
  id bigint generated by default as identity primary key,
  site_type text not null,
  login_id text not null,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.passwords enable row level security;

-- Create policies (assuming public access for this concept app, or authenticated if user logged in)
-- For this concept app, allowing full access to anon key for simplicity as per existing patterns
create policy "Allow all operations for anon"
on public.passwords for all
using (true)
with check (true);
